# Generated by Django 6.1 on 2026-08-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roverobservation',
            name='ph',
        ),
    ]
