# Generated by Django 6.1 on 2026-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_roverobservation_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverobservation',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roverobservation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roverobservation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roverobservation',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roverobservation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
