# Generated by Django 6.1 on 2026-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_roverobservation_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverobservation',
            name='sensor_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
