# Generated by Django 6.1 on 2026-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_roverobservation_sensor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverobservation',
            name='environmental_assessment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
